spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <put google client id here>
            client-secret: <put google client secret here>
          okta:
            client-id: <put okta client id here>
            client-secret: <put okta client secret here>
        provider:
          okta:
            issuer-uri: https://<okta domain>.oktapreview.com/oauth2/default
            authorization-uri: https://<okta domain>.oktapreview.com/oauth2/v1/authorize
            token-uri: https://<okta domain>.oktapreview.com/oauth2/v1/token
            user-info-uri: https://<okta domain>.oktapreview.com/oauth2/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://<okta domain>.oktapreview.com/oauth2/v1/keys
