spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <put google client id here>
            client-secret: <put google client secret here>
          okta:
            client-id: <put okta client id here>
            client-secret: <put okta client secret here>
        provider:
          okta:
            issuer-uri: https://<okta domain>.oktapreview.com/oauth2/default
